name: backend_dart
description: Backend en Dart con shelf, router, MySQL y dotenv
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2
  mime: ^1.0.5
  http_parser: ^4.0.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  mysql1: ^0.20.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
